const jsdom = require("jsdom");
const { JSDOM } = jsdom;

const dom = new JSDOM(`<!DOCTYPE html><html><body><div id="body-context_analysis"></div></body></html>`);
const document = dom.window.document;

const glossary = {'LLM narrative': 'A written interpretation generated by a language model.', 'Deterministic outputs': 'Metrics, tables, and plots produced directly by the ML pipeline rather than by a language model.'};
const narratives = {
    expert: {
        context_analysis: `<p>This study aims to assist pathologists in distinguishing benign from malignant breast masses using fine-needle aspirate (FNA) cell nuclei features derived from the UCI repository. While the model achieved a high ROC-AUC of 0.9748, indicating excellent discriminative power on this specific dataset, clinical readiness must be tempered by the fact that it was trained and evaluated entirely on historical public data without mention of external validation cohorts in the metadata provided.</p>\n<p>The user's objective to classify invasive ductal carcinoma faces inherent challenges: a class distribution where benign cases (0) comprise approximately 62.7% of the cohort, while malignant cases (1) make up roughly 37.4%. This imbalance necessitates strict reliance on metrics like Sensitivity and F1-score rather than raw accuracy when assessing safety profiles for cancer detection.</p>`
    }
};
let currentMode = 'expert';

function updateSection(key) {
    const bodyEl = document.getElementById('body-' + key);
    let html = narratives[currentMode][key] || '';
    
    html = html.replace(/<span class="tooltip-trigger">([\s\S]*?)<span class="tooltip-text">[\s\S]*?<\/span><\/span>/gi, '$1');
    html = html.replace(/<span class="glossary-term"[^>]*>([\s\S]*?)<\/span>/gi, '$1');

    if (glossary && Object.keys(glossary).length > 0) {
        for (const [term, data] of Object.entries(glossary)) {
            const escapedTerm = term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
            const regex = new RegExp(`(^|\\W)(${escapedTerm})(?=\\W|$)(?![^<]*>)`, 'gi');
            let defText = data;
            html = html.replace(regex, `$1<span class="tooltip-trigger">$2<span class="tooltip-text">${defText}</span></span>`);
        }
    }
    
    html = html.replace(/\[PLOT:\s*(.*?)\s*\]/gi, (match, plotKeysStr) => {
        return '';
    });

    html = html.replace(/<\/div>\s*<\/p>\s*<p>\s*<div class="inline-plots-container">/gi, '');
    html = html.replace(/<\/div>\s*<br\s*\/?>\s*<div class="inline-plots-container">/gi, '');
    html = html.replace(/<\/div>\s*<div class="inline-plots-container">/gi, '');

    bodyEl.innerHTML = html;
}

updateSection('context_analysis');
console.log(document.getElementById('body-context_analysis').innerHTML);
