import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from core.report.narrative_generator import NarrativeGenerator


def test_rule_based_fallback_is_transparent_notice_not_fake_analysis():
    narrative = NarrativeGenerator()._generate_rule_based(
        dataset_name="messy_clinical.csv",
        task_type="classification",
        metrics={"accuracy": 0.9067, "ROC-AUC": "0.7283"},
        visuals_summary={"confusion_matrix_png": {"path": "unused"}},
        imbalance_warning={
            "message": "Do not interpret accuracy alone as clinical readiness.",
        },
    )

    assert narrative["_meta"]["source"] == "narrative_unavailable"
    assert "not generated by an LLM" in narrative["expert"]["executive_summary"]
    assert "metric cards" in narrative["expert"]["findings"].lower()
    assert "| Metric | Value |" not in narrative["expert"]["findings"]
    assert narrative["layman"]["verdict"] == "Narrative Unavailable"
