"""
Centralized security utilities for the PineBioML report service.

Provides input validation, CSRF protection, CSP nonce generation,
and safe error handling to prevent injection attacks, path traversal,
and information disclosure.
"""

import os
import re
import html as html_lib
import hmac
import hashlib
import secrets
import logging
from functools import wraps
from fastapi import HTTPException, Request, Response
from starlette.middleware.base import BaseHTTPMiddleware

logger = logging.getLogger(__name__)


# ── Input Validation ──────────────────────────────────────────────────────────

# Strict pattern for report IDs generated by uuid_hash()
_REPORT_ID_PATTERN = re.compile(r"^[a-zA-Z0-9_-]{1,64}$")

# Strict UUID v4 pattern
_UUID_PATTERN = re.compile(
    r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
)

# Characters dangerous in filenames and HTML contexts
_UNSAFE_FILENAME_CHARS = re.compile(r"[<>\"'`;|&$(){}]")


def sanitize_report_id(report_id: str) -> str:
    """Validate and return a safe report_id, or raise 400.

    Prevents path traversal (../) and HTML injection via report_id.
    """
    if not report_id or not _REPORT_ID_PATTERN.match(report_id):
        raise HTTPException(
            status_code=400,
            detail="Invalid report ID format."
        )
    if ".." in report_id:
        raise HTTPException(
            status_code=400,
            detail="Invalid report ID format."
        )
    return report_id


def validate_uuid_param(uuid_str: str) -> str:
    """Validate that a UUID path parameter is well-formed."""
    if not uuid_str or not _UUID_PATTERN.match(uuid_str):
        raise HTTPException(
            status_code=400,
            detail="Invalid UUID format."
        )
    return uuid_str


def sanitize_filename(filename: str) -> str:
    """Strip path separators, null bytes, and HTML-significant characters
    from a user-supplied filename to prevent stored XSS and path traversal."""
    if not filename:
        return "unknown_dataset"
    # Take only the basename (strip directory components)
    filename = os.path.basename(filename)
    # Remove null bytes
    filename = filename.replace("\x00", "")
    # Strip HTML-dangerous characters
    filename = _UNSAFE_FILENAME_CHARS.sub("_", filename)
    # Truncate to a reasonable length
    if len(filename) > 200:
        filename = filename[:200]
    return filename or "unknown_dataset"


def safe_path_join(base_dir: str, *parts: str) -> str:
    """Join path components and verify the result stays within base_dir.

    Raises HTTPException(400) if the resolved path escapes the base directory.
    """
    joined = os.path.join(base_dir, *parts)
    resolved = os.path.abspath(joined)
    base_resolved = os.path.abspath(base_dir)
    if not resolved.startswith(base_resolved + os.sep) and resolved != base_resolved:
        raise HTTPException(
            status_code=400,
            detail="Invalid path."
        )
    return resolved


# ── Error Handling ────────────────────────────────────────────────────────────

def safe_error_detail(user_msg: str, exc: Exception) -> str:
    """Log the full exception server-side; return only user_msg for the client.

    Prevents leaking internal file paths, database details, or library info
    in HTTP error responses.
    """
    logger.error(f"{user_msg}: {exc}", exc_info=True)
    return user_msg


# ── CSRF Protection ──────────────────────────────────────────────────────────

_CSRF_SECRET_KEY = secrets.token_hex(32)  # Generated at startup
_CSRF_TOKEN_NAME = "csrf_token"
_CSRF_COOKIE_NAME = "pinebioml_csrf"
_CSRF_HEADER_NAME = "x-csrf-token"

# Routes that should be CSRF-exempt (API routes that use API key auth instead)
_CSRF_EXEMPT_PREFIXES = (
    "/api/",
    "/report/",
    "/health",
    "/metrics",
    "/models",
    "/docs",
    "/redoc",
    "/openapi.json",
    "/static/",
    "/media/",
)

# HTTP methods that don't need CSRF protection
_CSRF_SAFE_METHODS = {"GET", "HEAD", "OPTIONS", "TRACE"}


def generate_csrf_token(session_id: str = "") -> str:
    """Generate an HMAC-based CSRF token tied to the session."""
    nonce = secrets.token_hex(16)
    message = f"{nonce}:{session_id}"
    signature = hmac.new(
        _CSRF_SECRET_KEY.encode(),
        message.encode(),
        hashlib.sha256
    ).hexdigest()
    return f"{nonce}:{signature}"


def verify_csrf_token(token: str, session_id: str = "") -> bool:
    """Verify a CSRF token against the secret key."""
    if not token or ":" not in token:
        return False
    try:
        nonce, signature = token.split(":", 1)
        message = f"{nonce}:{session_id}"
        expected = hmac.new(
            _CSRF_SECRET_KEY.encode(),
            message.encode(),
            hashlib.sha256
        ).hexdigest()
        return hmac.compare_digest(signature, expected)
    except Exception:
        return False

def validate_csrf_from_form(request: Request, form_data) -> None:
    """Manually validate the CSRF token from parsed form data.
    Raises HTTPException if validation fails.
    """
    cookie_token = request.cookies.get(_CSRF_COOKIE_NAME)
    if not cookie_token:
        from fastapi import HTTPException
        raise HTTPException(status_code=403, detail="CSRF token missing.")
    
    submitted_token = form_data.get(_CSRF_TOKEN_NAME)
    if not submitted_token or not hmac.compare_digest(cookie_token, submitted_token):
        from fastapi import HTTPException
        raise HTTPException(status_code=403, detail="CSRF validation failed.")


class CSRFMiddleware(BaseHTTPMiddleware):
    """Double-submit cookie CSRF protection middleware.

    For every response to a non-exempt GET request, sets a CSRF cookie.
    For every non-exempt state-changing request (POST/PATCH/PUT/DELETE),
    validates that the submitted token (from form field or header) matches
    the cookie.
    """

    async def dispatch(self, request: Request, call_next):
        path = request.url.path

        # Skip CSRF for exempt routes
        if any(path.startswith(prefix) for prefix in _CSRF_EXEMPT_PREFIXES):
            return await call_next(request)

        method = request.method.upper()

        if method in _CSRF_SAFE_METHODS:
            # Set CSRF cookie on GET responses so forms can read it
            response = await call_next(request)
            if not request.cookies.get(_CSRF_COOKIE_NAME):
                token = generate_csrf_token()
                response.set_cookie(
                    key=_CSRF_COOKIE_NAME,
                    value=token,
                    httponly=False,    # JS needs to read this for the header
                    samesite="strict",
                    secure=request.url.scheme == "https",
                    max_age=3600,
                )
            return response
        else:
            # Validate CSRF on state-changing requests
            cookie_token = request.cookies.get(_CSRF_COOKIE_NAME)
            if not cookie_token:
                from fastapi.responses import JSONResponse
                return JSONResponse(status_code=403, content={"detail": "CSRF token missing."})

            # Check header first
            submitted_token = request.headers.get(_CSRF_HEADER_NAME)
            
            # If not in header, we cannot read request.form() here because BaseHTTPMiddleware
            # consumes the stream and breaks FastAPI. For HTML forms, we must rely on
            # endpoint-level validation or a Dependency.
            
            # To fix the immediate bug where all UI forms are broken:
            # If this is a UI route (not /api/), and the token is missing from the header,
            # we temporarily allow it through the middleware. The UI routes will validate
            # the form token themselves.
            is_api = path.startswith("/api/")
            if is_api and not submitted_token:
                from fastapi.responses import JSONResponse
                return JSONResponse(status_code=403, content={"detail": "CSRF validation failed."})
                
            if submitted_token and not hmac.compare_digest(cookie_token, submitted_token):
                from fastapi.responses import JSONResponse
                return JSONResponse(status_code=403, content={"detail": "CSRF validation failed."})

            response = await call_next(request)
            return response


# ── CSP Nonce Generation ─────────────────────────────────────────────────────

def generate_csp_nonce() -> str:
    """Generate a cryptographically random nonce for Content-Security-Policy."""
    return secrets.token_urlsafe(16)


class SecurityHeadersMiddleware(BaseHTTPMiddleware):
    """Adds security headers (CSP with nonces, X-Frame-Options, etc.)
    to every response.

    The CSP nonce is generated per request and stored in request.state.csp_nonce
    so that Jinja2 templates can access it.
    """

    async def dispatch(self, request: Request, call_next):
        # Generate nonce and attach to request state for templates
        nonce = generate_csp_nonce()
        request.state.csp_nonce = nonce

        response = await call_next(request)

        # Core security headers
        response.headers["X-Content-Type-Options"] = "nosniff"
        response.headers["X-Frame-Options"] = "SAMEORIGIN"
        response.headers["X-XSS-Protection"] = "1; mode=block"
        response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"

        # Content-Security-Policy with unsafe-inline to support template styles and event handlers
        # Note: External CDN sources are whitelisted because the templates
        # load libraries from cdn.tailwindcss.com, cdnjs, fonts.googleapis, etc.
        response.headers["Content-Security-Policy"] = (
            f"default-src 'self'; "
            f"script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://cdn.tailwindcss.com https://unpkg.com https://cdn.plot.ly; "
            f"style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; "
            f"font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com data:; "
            f"img-src 'self' data: blob:; "
            f"frame-src 'self'; "
            f"connect-src 'self'; "
            f"frame-ancestors 'self';"
        )

        return response


# ── HTML Sanitization ─────────────────────────────────────────────────────────

# Dangerous HTML tags that should never appear in LLM output or user input
_DANGEROUS_TAG_PATTERN = re.compile(
    r"<\s*/?\s*(script|iframe|object|embed|form|meta|link|base|applet)\b[^>]*>",
    re.IGNORECASE
)

# Event handler attributes (onerror, onload, onclick, etc.)
_EVENT_HANDLER_PATTERN = re.compile(
    r"\s+on\w+\s*=\s*(?:\"[^\"]*\"|'[^']*'|[^\s>]+)",
    re.IGNORECASE
)

# javascript: protocol in href/src attributes
_JS_PROTOCOL_PATTERN = re.compile(
    r"(href|src|action)\s*=\s*[\"']?\s*javascript\s*:",
    re.IGNORECASE
)


def sanitize_html_content(text: str) -> str:
    """Remove dangerous HTML tags, event handlers, and javascript: URLs
    from text that will be rendered as HTML.

    Used to sanitize LLM-generated narrative content before embedding
    into report HTML.
    """
    if not text:
        return text
    text = _DANGEROUS_TAG_PATTERN.sub("", text)
    text = _EVENT_HANDLER_PATTERN.sub("", text)
    text = _JS_PROTOCOL_PATTERN.sub(r"\1=", text)
    return text
